sudo: false
dist: trusty
language: php

cache:
  directories:
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "wirecard"

php:
  - 7.1
  - 7.0
  - 5.6

env:
  global:
  - secure: ${SONAR_TOKEN}
  - COMPOSER_ARGS="--no-interaction"
  - github_token:
      secure: "GrPeKimeHRXL7Bl1ORmmnbKRBsJP/c3kfuK9+KjfjuJYLXQDjar1duVzLLG3ErjFdas0H5W8stNi/120XH8/fwIK/PCjr828cGIkqzkV1hXbj8uWKnf3O8unxwzAyMCQNXjsmcQA0ubxTzxkgJXfWzNtwHYv/dVvu8aq5KrdOGWKBjyiqAFX7tb7/NoINrqr1CkmRvq4V4sPoErpUT0VMmptTmFfx5XY3XngkbMiRWpJR1Fjqvx3FnN65EXi0/jZ2LJSmqdPM41O0WZv0TwoR5gjsC/YF0QqFrYHAEJsiEbkmVgn9fTx/qrW+wJqsCDy3O9sGr749nNb6/qy7+2hsenAiZeTFU7J0dJCo4B1+OZOP6aFU+sGDlXzZaStydOR+p7jfizq2W1imlaZ7nybqzZTO78Yui+NP+UWOB5TQsJkjVa2XaVkLV7UCTE8a8omnVcoQ2RGgRNQl5FwxFLq6UjqerxLp1ftyGDLDHdg8gwTt5GT+e+ucUC5SRAQDzMeIaKkcAddH/dYKd8+cD3+h1eN6DUPwKV9Gh5SpDG19ndJDlrVAnqe36C4sjGf2+D8W06T8b4sVwkZvWIXJT1voHwJI4bkGM6xvfGqMuDwFRY5EMDke2PRsbCqPoWAhOfY97KA7CoQn6n1ze/wpJu2qOiMcU52TiXkdTB6nmZMtYk="

install:
  - travis_retry composer require --dev $COMPOSER_ARGS
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer test-coverage
  - composer cs-check
  - sonar-scanner

after_script:
   - travis_retry composer upload-coverage